### ISSUE TITLE
JSXC Installation

### ISSUE THREAD

**Issue by mikygee** [jsxc/jsxc.roundcube#10]
Hello,

I really didn't understand how to install JSXC with roundcube.

Roundcube ans xmpp server are on the same machine. This machine is behind a reverse proxy.

a) What should I write for URL ? 127.0.0.1 will go locally, mydomain.org will go to the reverse proxy and come back
b) What if i have multiple domains ?
c) I don't understand how login in to roundcube will recognize and authenticate my user ? Should I have the same password for roundcube and xmpp server ?

From the configuration file
$config['jsxc'] = array(
    'xmpp' => array(
        'url' => 'https://127.0.0.1/http-bind/',
        'domain' => 'mydomain.org',
        'resource' => 'JSXC',
        'overwrite' => true,
        'onlogin' => false
    ),
    'RTCPeerConfig' => array(
        'iceServers' => array(
            array(
                'urls' => 'stun:stun.l.google.com:19302'
            )
        )
    )
);

**Comment by damkh** [comment]
Hello @mikygee 
a) Try to set 
`'url' => '/http-bind/',`
or
`'url' => 'https://mydomain.org/http-bind/',`
The link https://mydomain.org/http-bind/ should be accessible as well as the link to the Roundcube page
b) Do your multiple domains work on one Roundcube instance?

**Comment by ObaSensei** [comment]
I have this same issue I have cant install JSXC and have ejabberd runing nd accesible from admin

**Comment by sualko** [comment]
@ObaSensei you have to provide more information. How is your setup? What did you try already? Do you have any errors? Which parts are already working? To not disturb the original author, it would be great if you could open a new issue with the required information.
