### ISSUE TITLE
Possible Authentication Issue

### ISSUE THREAD

**Issue by etchtech** [jsxc/jsxc.roundcube#11]
I currently have a server setup for myself that has Dovecot/Postfix for email, Roundcube for a webclient, Prosody for XMPP.  Each of these is currently function and authenticating through Dovecot SASL which authenticates with the system (passwd).

I am attempting to add the JSXC plugin for Roundcube but it doesn't activate the plugin.  Upon further troubleshooting I have found that when JSXC tries to authenticate, it (or BOSH via Prosody) sends the format [user@domain][user][password] to which Dovecot SASL says FAIL.

I then tried Pidgin and when it sends the same authorization request, it sends [user][password], but it is actually successful in signing in.

Here is my config.inc.php:
```
// Use config.php.inc to configure deployment-specific options.

// The syntax is the same; JSXC configs from both files will be merged.

$config['jsxc'] = array(
    'xmpp' => array(
        'url' => '/http-bind/',
        'domain' => '<DOMAIN>',
        'resource' => 'JSXC',
        'overwrite' => true,
        'onlogin' => false
    )
);
```

Here is the browser console output:
```
State changed to ESTABLISHING 			jsxc.js:184:9
New connection 					jsxc.js:184:9
CONNECTING: null 				jsxc.js:184:9
AUTHFAIL: null 					jsxc.min.js:1:2054
Navigated to https://<HOST>/roundcube/?_task=login
State changed to INITIATING 			jsxc.min.js:1:2054
Try to relogin 					jsxc.min.js:1:2054
Logout was forced or I found no valid jid 	jsxc.min.js:1:2054
State changed to SUSPEND
```

And finally the Prosody logging of the events:
```
Nov 14 14:08:12 socket  debug   server.lua: auto-starting ssl negotiation...
Nov 14 14:08:12 socket  debug   server.lua: attempting to start tls on tcp{client}: 0x55fd22f0a728
Nov 14 14:08:12 socket  debug   server.lua: accepted new client connection from 127.0.0.1:41796 to 5281
Nov 14 14:08:12 socket  debug   server.lua: ssl handshake done
Nov 14 14:08:12 http.server     debug   Firing event: POST <HOST>/http-bind/
Nov 14 14:08:12 mod_bosh        debug   Handling new request table: 0x55fd22e23a10: <body rid='2634691805' xmlns='http://jabber.org/protocol/httpbind' to='<DOMAIN>' xml:lang='en' wait='60' hold='1' content='text/xml; charset=utf-8' ver='1.6' xmpp:version='1.0' xmlns:xmpp='urn:xmpp:xbosh'/>
----------
Nov 14 14:08:12 mod_bosh        debug   BOSH body open (sid: <none>)
Nov 14 14:08:12 bosh8f4857b3-3e19-491e-a9a2-52b51598cc9b        debug   BOSH session created for request from <CLIENT_IP>
Nov 14 14:08:12 mod_bosh        info    New BOSH session, assigned it sid '8f4857b3-3e19-491e-a9a2-52b51598cc9b'
Nov 14 14:08:12 mod_bosh        debug   We have an open request, so sending on that
Nov 14 14:08:12 mod_bosh        debug   Request destroyed: table: 0x55fd232ad1a0
Nov 14 14:08:12 bosh8f4857b3-3e19-491e-a9a2-52b51598cc9b        debug   BOSH session marked as inactive (for 60s)
Nov 14 14:08:12 mod_bosh        debug   Session 8f4857b3-3e19-491e-a9a2-52b51598cc9b has 0 out of 1 requests open
Nov 14 14:08:12 mod_bosh        debug   and there are 0 things in the send_buffer:
Nov 14 14:08:13 http.server     debug   Firing event: POST <HOST>/http-bind/
Nov 14 14:08:13 mod_bosh        debug   Handling new request table: 0x55fd22cadf60: <body rid='2634691806' xmlns='http://jabber.org/protocol/httpbind' sid='8f4857b3-3e19-491e-a9a2-52b51598cc9b'><auth xmlns='urn:ietf:params:xml:ns:xmpp-sasl' mechanism='PLAIN'>**<brian@<DOMAIN>brian[password]>**</auth></body>
----------
Nov 14 14:08:13 mod_bosh        debug   BOSH body open (sid: 8f4857b3-3e19-491e-a9a2-52b51598cc9b)
Nov 14 14:08:13 mod_bosh        debug   BOSH stanza received: <auth mechanism='PLAIN' xmlns='urn:ietf:params:xml:ns:xmpp-sasl'>

Nov 14 14:08:13 bosh8f4857b3-3e19-491e-a9a2-52b51598cc9b        debug   Received[c2s_unauthed]: <auth mechanism='PLAIN' xmlns='urn:ietf:params:xml:ns:xmpp-sasl'>
Nov 14 14:08:13 <DOMAIN>:auth_dovecot       debug   sending "AUTH   8       PLAIN   service=xmpp    resp=**<brian@<DOMAIN>brian[password]>**"
Nov 14 14:08:15 <DOMAIN>:auth_dovecot       debug   received "FAIL  8       user=brian"
Nov 14 14:08:15 <DOMAIN>:saslauth   debug   sasl reply: <failure xmlns='urn:ietf:params:xml:ns:xmpp-sasl'><not-authorized/></failure>
Nov 14 14:08:15 mod_bosh        debug   We have an open request, so sending on that
Nov 14 14:08:15 mod_bosh        debug   Request destroyed: table: 0x55fd2328f6a0
Nov 14 14:08:15 bosh8f4857b3-3e19-491e-a9a2-52b51598cc9b        debug   BOSH session marked as inactive (for 60s)
Nov 14 14:08:15 mod_bosh        debug   Session 8f4857b3-3e19-491e-a9a2-52b51598cc9b has 0 out of 1 requests open
Nov 14 14:08:15 mod_bosh        debug   and there are 0 things in the send_buffer:
```

Any guidance or assistance would be greatly appreciated!

**Comment by damkh** [comment]
Hello @etchtech 
Did you try to connect JSXC directly to your XMPP-server (not as a roundcube plugin, but as a standalone js-application) ?

**Comment by etchtech** [comment]
I haven't yet, but I will give it a go today

**Comment by etchtech** [comment]
I followed these instructions:  [https://github.com/jsxc/jsxc/wiki/Install-jsxc](https://github.com/jsxc/jsxc/wiki/Install-jsxc)

I got the same results in my Prosody logs, the format that BOSH receives and passes to Dovecot SASL for authentication includes the email address (or username@domain at least) before the username and password.

I am using mmencode -u to decrypt the authentication string.

**Comment by damkh** [comment]
Could you please print authentication sections in configuration files of Prosody and Dovecot?

**Comment by etchtech** [comment]
Dovecot (output from doveconf -n and I removed the non-authentication bits)
```
auth_username_format = %Ln

passdb {
  driver = pam
}
service auth {
  unix_listener /var/spool/prosody/private/auth-client {
    group = prosody
    mode = 0660
    user = prosody
  }
}

userdb {
  driver = passwd
}
```
And from Prosody
```
authentication = "dovecot"
dovecot_auth_socket = "/var/spool/prosody/private/auth-client"
```

**Comment by sualko** [comment]
Can you test if BOSH via Pidgin is working?

**Comment by etchtech** [comment]
Yes, it is successful.

That is how I noticed that the authentication information is different.

**Comment by sualko** [comment]
> Yes, it is successful

Just to make it absolutely clear: You used BOSH in pidgin instead of a normal socket connection? Because the last one is standard. Can you send me some test credentials to klaus@jsxc.org, so I can check it by myself?

**Comment by etchtech** [comment]
Yes, I tested out both BOSH and the normal socket connection before I started working on the Roundcube plugin.

Credentials sent in email with subject 'JSXC/Roundcube Issue #11'

**Comment by sualko** [comment]
According to [SASL PLAIN](https://tools.ietf.org/html/rfc4616) the auth string should be in the format `[authzid] UTF8NUL authcid UTF8NUL passwd`. StropheJS, the underlying XMPP library, is [setting authzid to the bare jid](https://github.com/strophe/strophejs/blob/16358a1e99fe6c33fbd8f3507081113f56605402/src/core.js#L1768), which seams conform to the standard. Pidgin on the other hand [omits the value](https://github.com/tieto/pidgin/blob/94bbd78ebe91a874fef4432decb3a30e67ebc2bb/libpurple/protocols/jabber/auth_plain.c#L46). There is a similar issue still open in the strophe repository: strophe/strophejs#307. Maybe you can ask there, but I assume it's a problem with your authentication backend.

The quick and dirty fix would be to replace the corresponding connect method and set authzid to an empty string. Just execute the following code after you loaded `jsxc.dep.js`.

```
Strophe.Connection.prototype.connect = function (jid, pass, callback, wait, hold, route, authcid) {
        this.jid = jid;
        /** Variable: authzid
         *  Authorization identity.
         */
        this.authzid = '';

        /** Variable: authcid
         *  Authentication identity (User name).
         */
        this.authcid = authcid || Strophe.getNodeFromJid(this.jid);

        /** Variable: pass
         *  Authentication identity (User password).
         */
        this.pass = pass;

        /** Variable: servtype
         *  Digest MD5 compatibility.
         */
        this.servtype = "xmpp";

        this.connect_callback = callback;
        this.disconnecting = false;
        this.connected = false;
        this.authenticated = false;
        this.restored = false;

        // parse jid for domain
        this.domain = Strophe.getDomainFromJid(this.jid);

        this._changeConnectStatus(Strophe.Status.CONNECTING, null);

        this._proto._connect(wait, hold, route);
    }
```

Nonetheless I will close this issue, because it can't be fixed by JSXC. If you make any progress it would be awesome if you could share it with us.

**Comment by etchtech** [comment]
Thanks for taking a look, I will work with that!
