### ISSUE TITLE
Plugin not loaded

### ISSUE THREAD

**Issue by aacunha** [jsxc/jsxc.roundcube#3]
After enable jsxc plugin on roundcube 1.3.0, the plugin was not loaded, and i get those errors:

console:
print screen
![captura de tela de 2017-07-04 15 24 45](https://user-images.githubusercontent.com/5031111/27840151-246d72c6-60cd-11e7-929a-98338fd086c6.png)

nginx logs:
2017/07/04 14:40:37 [error] 2733#0: *50132208 FastCGI sent in stderr: "PHP message: PHP Warning:  stat(): stat failed for /var/www/roundcubemail-teste/plugins/jsxc/css/jsxc.roundcube.css in /var/www/roundcubemail-1.3.0/plugins/jsxc/jsxc.php on line 35" while reading response header from upstream, client: 10.110.5.8, server: webmailteste.xxx.xxx, request: "GET /plugins/jsxc/jsxc.min.js HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "webmailteste.xxx.xxx.xxx", referrer: "https://webmailteste.xxx.xxx/"

**Comment by aacunha** [comment]
@dteleguin can you help me?

**Comment by dteleguin** [comment]
@aacunha hi, sorry for delay, I'll look into this issue soon.

**Comment by yennor** [comment]
had the same problem. Commented out the lines in jsxc.php which want to load jsxc.roundcube.css, and still get the same javascript problem about jsxc not beeing defined.
Roundcube loads, but the list with received mails stays empty...
using roundcube 1.2.3

**Comment by dteleguin** [comment]
Could anyone please test again? The issue should go away with latest updates.

**Comment by aacunha** [comment]
@dteleguin working now!
