### ISSUE TITLE
Install procedure not working

### ISSUE THREAD

**Issue by aacunha** [jsxc/jsxc.roundcube#4]
The installation with composer is not working:

root@webmail2:/var/www/roundcubemail-teste# php composer.phar install
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package jsxc/jsxc could not be found in any version, there may be a typo in the package name.

Potential causes:

Only i can get the plugin via git clone

**Comment by yennor** [comment]
i've got exactly the same problem, add
        {
            "type": "vcs",
            "url": "https://github.com/jsxc/jsxc.roundcube.git"
        }

to composer.json under repositories

**Comment by freakyc** [comment]
I added the above and it still wouldn't install.  I ended up adding
`"minimum-stability": "dev",`
to composer.json and then ran
`php composer.phar update`
and it installed

I figured there was a better way to install it so I changed  the line to
`"minimum-stability": "stable",`
and then changed 
`"jsxc/jsxc": ">=1.0"`
to
`"jsxc/jsxc": "@dev"`

It's updated properly now after running
`php composer.phar update`
so I assume it would've installed properly in the first place.

**Comment by dteleguin** [comment]
Sorry for making you wait. The procedure should work now as described in README, please test.

**Comment by aacunha** [comment]
@dteleguin , is working now (tested on roundcube 1.3.3)! Thanks!!!
