### ISSUE TITLE
Rosterappend

### ISSUE THREAD

**Issue by aacunha** [jsxc/jsxc.roundcube#6]
@dteleguin , in the config.inc.php we have option of rosterappend = body:

    'rosterAppend' => 'body',

I cannot find the documentation of jsxc another value to the roster, and the option of start minimized dont work:
 'startMinimized' => 'false'

how can i start the jsxc in one way what the user can minimize the chat window? Now its stay fixed on right side, and the users cannot logoff or access the preferences of webmail, because the chat stay on it.

**Comment by dteleguin** [comment]
@aacunha , if you want the roster to be minimized upon startup, you should set the above option to true:
```
$config['jsxc'] = array(
    'loginForm' => array(
        'form' => '#login-form > div > form',
        'jid' => '#rcmloginuser',
        'pass' => '#rcmloginpwd'
    ),
    'rosterAppend' => 'body',
    'startMinimized' => true,
    'root' => 'plugins/jsxc'
);
```
To minimize/restore the roster, you need to click a vertical strip by the left side of the roster. It appears when you hover your mouse above it. Yep its not that obvious, but its definitely out of the scope of RoundCube+JSXC integration :)

**Comment by aacunha** [comment]
@dteleguin i Made some some modification on roundcube and jsxc css, now its ok for me:



ROUNDCUBE
#mainscreen 
right: 228px


JSXC
#jsxc_roster
margin-top: 69px

#jsxc_toggleRoster:before
border-width 11px 8px 11px 0

**Comment by dteleguin** [comment]
OK to close the issue?

**Comment by aacunha** [comment]
ok, thanks for your support
