### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by aacunha** [jsxc/jsxc.roundcube#7]
@dteleguin , the jsxc already have the translation to pt_BR. How can i merge this into jsxc.roundcube?

https://github.com/jsxc/jsxc/blob/master/locales/pt-BR.json

**Comment by dteleguin** [comment]
Confirmed, I've changed the locale to pt-BR, and JSXC switched to English,
despite pt-BR being present in `lib/translation.js`. Other languages work well nevertheless. @sualko , can you help here?

**Comment by sualko** [comment]
I have no glue, why this is not working, but I will look at it next week. If I don't respond, please remind me.

Btw. @dteleguin thanks for your effort :tada:

**Comment by aacunha** [comment]
@sualko , i found some discrepances on files, in one file the language code is "pt-br" and in another "pt_br". By the way, the correct language code is "pt_BR":


**pt-br**
./lib/jsxc.dep.min.js.map
./lib/translation.js
./lib/jsxc.dep.js
./lib/jsxc.dep.min.js

**pt_br**
./lib/jsxc.dep.js
./lib/jsxc.dep.min.js

**Comment by sualko** [comment]
Can you test if changing `pt-BR` to `pt_BR` in `lib/translations.js` fixes your issue?

**Comment by aacunha** [comment]
I tried to chage to pt_BR in translations.js and in another try in all occurrences (antoher files too) without success.

**Comment by dteleguin** [comment]
@sualko @aacunha guys, if you have standalone JSXC demo deloyed somewhere, could you please test pt-BR? If the bug is observed outside of RoundCube, we should probably close this bug and open a new one at jsxc/jsxc.

**Comment by aacunha** [comment]
@dteleguin i dont have jsxc install, i can try to install. I tried another languages (es, it, ...) and the plugin remain in english. In your installation other languages works?

**Comment by dteleguin** [comment]
@aacunha , did you make sure the language is on the top of the language list in the prefs? (i.e. has the highest priority)

I've tested both with JSXC standalone and RoundCube plugin. It's a JSXC bug, see https://github.com/jsxc/jsxc/issues/646

**Comment by aacunha** [comment]
@dteleguin, yes.
![captura de tela de 2017-12-11 18 59 54](https://user-images.githubusercontent.com/5031111/33853565-8b8e8e76-dea5-11e7-99a5-7dd3d387a88f.png)

**Comment by aacunha** [comment]
Fellows, how fix in jsxc.roundcube the same solution of https://github.com/jsxc/jsxc/issues/646 ?

**Comment by sualko** [comment]
@aacunha you have to wait for the next jsxc release and that someone merges it to the roundcube app.
