### ISSUE TITLE
Jsxc not loading in some page

### ISSUE THREAD

**Issue by aacunha** [jsxc/jsxc.roundcube#8]
The plugin is working very well, but in some pages of roundcube the plugin was not load, for example in the pages:

Calendar and reading email.

![captura de tela de 2017-12-08 10 31 11](https://user-images.githubusercontent.com/5031111/33766052-ed618a04-dc02-11e7-9073-a328ef0abd52.png)

![captura de tela de 2017-12-08 10 29 22](https://user-images.githubusercontent.com/5031111/33766021-d098be10-dc02-11e7-9e69-e67747cedce5.png)

![captura de tela de 2017-12-08 10 26 54](https://user-images.githubusercontent.com/5031111/33766022-d0c72c82-dc02-11e7-86f8-61a2bbb4d5f0.png)

**Comment by sualko** [comment]
Can you check if you have any errors in your javascript console?

**Comment by aacunha** [comment]
no error on console
![captura de tela de 2017-12-08 10 49 41](https://user-images.githubusercontent.com/5031111/33766658-a98b53e8-dc05-11e7-9f5b-c7b780a8371f.png)

**Comment by aacunha** [comment]
solved in my enviroment changing the switch in function on_render_page($args) to (in this mode the chat is loaded in every page, even on plugins page as calendar, password, managesieve, etc):


    function on_render_page($args) {

        switch($args['template']) {

            case 'login':
                $this->load_jsxc();
                break;

            case 'logoff':
                $this->api->output->add_script("
                    $('.button-logout').each(function(i, b) {
                        var onclick = b.onclick;
                        b.onclick = function(e) {
                            e.stopPropagation();
                            e.preventDefault();
                            if (jsxc.xmpp.conn != null) {
                                $(document).on('disconnected.jsxc', onclick);
                                jsxc.xmpp.logout(true);
                            } else {
                                onclick();
                            }
                        }
                    });
                ", 'foot');
                break;

            case 'mail':
            case 'calendar':
            case 'compose':
            case 'addressbook':
            case 'settings':
            case 'folders':
            case 'identities':
            case 'responses':
            case 'about':
                $this->load_jsxc();
                $this->api->output->add_script("
                    $('.button-logout').each(function(i, b) {
                        var onclick = b.onclick;
                        b.onclick = function(e) {
                            e.stopPropagation();
                            e.preventDefault();
                            if (jsxc.xmpp.conn != null) {
                                $(document).on('disconnected.jsxc', onclick);
                                jsxc.xmpp.logout(true);
                            } else {
                                onclick();
                            }
                        }
                    });
                ", 'foot');
                break;

            default:
                $this->load_jsxc();
                $this->api->output->add_script("
                    $('.button-logout').each(function(i, b) {
                        var onclick = b.onclick;
                        b.onclick = function(e) {
                            e.stopPropagation();
                            e.preventDefault();
                            if (jsxc.xmpp.conn != null) {
                                $(document).on('disconnected.jsxc', onclick);
                                jsxc.xmpp.logout(true);
                            } else {
                                onclick();
                            }
                        }
                    });
                ", 'foot');
                break;
        }

    }

**Comment by dteleguin** [comment]
@aacunha ,

The reason to restrict JSXC plugin to the explicit list of tepmlates like mail/calendar/compose/etc. was to avoid loading JSXC in iframes (message preview, contact details etc.) By copying the code to the "default" case you've effectively enabled JSXC on *every* template, including iframes.

In older versions of JSXC, this resulted in roster showing both in the main RC window *and* inside message preview. In 3.3.x, it fails to show, but the JSXC code is still loaded, which affects overall performance.

Meanwhile, I've implemented more concise and universal approach without explicit list of allowed templates. Could you please test it from git master?

**Comment by dteleguin** [comment]
@aacunha , just curious, what was the reason to introduce the "logoff" case? From my experience, logout functionality works OK without this modification.

**Comment by aacunha** [comment]
@dteleguin Really just letting the default work, actually had done that after closing the issue. I had included the logoff code to "force" terminate the xmpp connection, as some users end up opening webmail in 2 browser tabs, generating unexpected results. It would just be a way to prevent the plugin from loading inappropriately on the login page.

As I emailed you, how could I not load the plugin on the login screen? We use authentication plugins such as rcguard and twofactor_gauthenticator, and jsxc ends up loading when the user, for example, misses the password a few times and falls into the captcha, enters the correct password after that and forgets to validate the captcha.

in the Two factor if the browser is not saved, jsxc also still loads in the login screen.

Would I have to avoid such cases? I tried in jsxc.php not to load the plugin in the "login" screen, but this way the plugin loads into the "mail" screen without the user credentials, so the xmpp session does not start.

**Comment by dteleguin** [comment]
@aacunha , I think I've understood the problem. Simply put, if the login process is comprised of several phases, like login+password first and captcha/OTP next, JSXC login succeeds right at the first phase and then shows on the second screen, which is undesirable. Did I get it right? I think we should open another issue for it, hopefully @sualko gives some insight.

OK to close this issue?

**Comment by aacunha** [comment]
@dteleguin , thats right! i will open another issue explaining this. 

To ilustrate why i included the "logoff" case, folow the printscreen on my first login today on webmail: 
![captura de tela de 2017-12-13 09 51 49](https://user-images.githubusercontent.com/5031111/33938490-c1280716-dfee-11e7-815e-41c7e7837e83.png)
